baseURL = "https://ccqqder.github.io/PeachPitBoat/"
theme = "blowfish"
defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
hasCJKLanguage = true
enableEmoji = true
summaryLength = 0

[pagination]
  pagerSize = 5

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
