disabled = false
languageCode = "zh-tw"
languageName = "繁體中文"
weight = 1
title = "核舟"

[params]
  displayName = "繁體中文"
  isoCode = "zh-TW"
  dateFormat = "2006年1月2日"
  description = "核舟 — 興趣使然的開發者將自己做的小玩意丟進海里的記錄"

[params.author]
  name = "QQder"
  image = "img/author.gif"
  headline = "核舟 — 數位古玩"
  bio = "AI 算力以後會被壟斷嗎？AI能力還會持續突破嗎？不管答案是什麼都要越早使用越好。這裡記錄一個文科背景 Sysadmin 靠 AI 協助開發iOS App。"
  links = [
    { github = "https://github.com/ccqqder" },
    { email = "mailto:qqder339@gmail.com" },
  ]
